### PR TITLE
remove travis branches

### PR DESCRIPTION
**Pull request by marutosi**
PR: #2638

with the update to the contribution guidelines we should start to clean
up the branches and remove the restriction for TravisCI to build only
certain branches.

Developers are encouraged to fork the main repo and configure their own
travis builds.

Signed-off-by: Florian Kraft <f.kraft at finn.de>

### CODE REVIEW

**Comment by marutosi** [comment]
What is status?

**Comment by marutosi** [comment]
What is status?

**Comment by marutosi** [comment]
What is status?

**Comment by marutosi** [comment]
What is status?

**Comment by marutosi** [comment]
What is status?

**Comment by basiszwo** [comment]
Sorry, I did not get updates on this via email :unamused: 
Can you please create the pull request against `opf/dev`. Also there's a rebase / merge issue. I'll point to it.

**Comment by marutosi** [comment]
> Can you please create the pull request against opf/dev

I am blocked.

**Pull request closed without merging**
